# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  default = {
    pname = "default";
    version = "v1.25.0";
    src = fetchFromGitHub {
      owner = "adap";
      repo = "flower";
      rev = "v1.25.0";
      fetchSubmodules = false;
      sha256 = "sha256-nsmlZt6lwUqMznu2GxZQsWUdL6EuibiEjN/w2LHr8eo=";
    };
  };
}
